name: laser_planner
description: App para dibujar plantas usando medidor laser Mileseey M120-B / M130
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  permission_handler: ^11.3.1
  pdf: ^3.11.0
  printing: ^5.13.1
  path_provider: ^2.1.4
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
