name: laser_planner
description: App para dibujar plantas con medidor laser
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.35.5
  permission_handler: 11.3.1
  pdf: 3.11.1
  printing: 5.13.2
  path_provider: 2.1.4
  share_plus: 10.0.2
  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
